### PR TITLE
add mac os build

### PR DESCRIPTION
**Pull request by oliver-sanders**
[@izahn](https://github.com/izahn/)

Hi, I've expanded the meta.yaml to add a build for Mac OS.

Tried `conda-build .; conda install -c <conda-bld> enchant` locally and tested with pyenchant. Appeared to work.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by oliver-sanders** [comment]
@conda-forge-admin, please rerender

**Comment by izahn** [comment]
I think this probably just needs a newer osx sdk as documented at https://conda-forge.org/docs/maintainer/knowledge_base.html?highlight=macosx_sdk_version#requiring-newer-macos-sdks

**Comment by izahn** [comment]
@conda-forge-admin please rerender

**Comment by izahn** [comment]
Looks good @oliver-sanders thanks for doing this! Anything else you want to do before I merge it?

**Comment by oliver-sanders** [comment]
There's a note in the docs to contact the "core team" before doing this so I'll pop a message on the conda-forge gitter and see what they say.

**Comment by oliver-sanders** [comment]
No response on gitter, I guess go with it?

Cheers.

**Pull request merged**
